[project]
name = "splinart"
version = "0.1.0"
description = "Add a short description here"
authors = ["Loic Gouarin <loic.gouarin@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]
clean = { cmd = "ninja -C .build -t clean" }
configure = { cmd = "cmake -G Ninja -S . -B .build -DCMAKE_BUILD_TYPE=Release" }
configure_test = { cmd = "cmake -G Ninja -S . -B .build -DBUILD_TESTS=ON" }
build_ninja = { cmd = "ninja -C .build" }
build = { depends-on = ["configure", "build_ninja"] }
build_test = { depends-on = ["configure_test", "build_ninja"] }
start = { cmd = ".build/splinart-cpp", depends-on = ["build"] }
test = { cmd = ".build/tests/test_splinart", depends-on = ["build_test"] }
doc = { cmd = "cd doc; make html" }

[dependencies]
cxx-compiler = ">=1.9.0,<2"
cmake = ">=3.31.5,<4"
opencv = ">=4.10.0,<5"
cli11 = ">=2.4.2,<3"
xtensor = ">=0.25.0,<0.26"
ninja = ">=1.12.1,<2"
clang-tools = ">=18.1.8,<20"
clang-format = ">=18.1.8,<20"
pre-commit = ">=4.1.0,<5"
gtest = ">=1.15.2,<2"
sphinx = ">=8.1.3,<9"
pydata-sphinx-theme = ">=0.16.1,<0.17"
doxygen = ">=1.12.0,<2"
breathe = ">=4.35.0,<5"
myst-parser = ">=4.0.0,<5"
cppcheck = ">=2.16.0,<3"
