
:: Remove some directories from PATH
set "PATH=%PATH:C:\ProgramData\Chocolatey\bin;=%"
set "PATH=%PATH:C:\Program Files (x86)\sbt\bin;=%"
set "PATH=%PATH:C:\Rust\.cargo\bin;=%"
set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%"
set "PATH=%PATH:C:\Program Files\Git\cmd;=%"
set "PATH=%PATH:C:\Program Files\Git\mingw64\bin;=%"
set "PATH=%PATH:C:\Program Files (x86)\Subversion\bin;=%"
set "PATH=%PATH:C:\Program Files\CMake\bin;=%"
set "PATH=%PATH:C:\Program Files\OpenSSL\bin;=%"
set "PATH=%PATH:C:\Strawberry\c\bin;=%"
set "PATH=%PATH:C:\Strawberry\perl\bin;=%"
set "PATH=%PATH:C:\Strawberry\perl\site\bin;=%"
set "PATH=%PATH:c:\tools\php;=%"
set "PATH=%PATH:C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;=%"
set "PATH=%PATH:C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;=%"
set "PATH=%PATH:C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;=%"
set "PATH=%PATH:C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;=%"
set "PATH=%PATH:C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;=%"
set "PATH=%PATH:C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;=%"
