name: "CI"

on:
    workflow_dispatch:
    pull_request:

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: false
          matrix:
            os:
              - windows-2022
              - ubuntu-22.04
              - macos-12
        steps:
            - uses: actions/checkout@v3

            - uses: prefix-dev/setup-pixi@v0.4.1
              with:
                pixi-version: v0.9.1
                cache: true

            - if: runner.os == 'Windows'
              run: pixi add --platform win-64 vc
            - run: pixi run build