name: Publish on conda

on:
  workflow_dispatch:
  pull_request:
  release:
    types: published

jobs:
    upload_on_conda:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    # - windows-latest
        steps:
            - uses: actions/checkout@v1

            - uses: prefix-dev/setup-pixi@v0.4.1
              with:
                pixi-version: v0.9.1
                cache: true

            - name: Install conda-build and anaconda-client
              run: pixi add conda-build anaconda-client

            - name: Set version
              run: |
                VER=$(cat version.txt)
                echo "VERSION=$VER" >> $GITHUB_ENV

            - name: Build the recipe
              shell: pixi run bash {0}
              run: conda build conda/recipe

            - name: upload on conda
              if: github.event_name == 'release'
              shell: pixi run bash {0}
              run: anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload --force $HOME/conda-bld/*/splinart-*.tar.bz2
